# Generated by Django 4.2.9 on 2026-03-25 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('sets_count', models.PositiveSmallIntegerField(default=3)),
                ('reps_hint', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('arms', 'Руки'), ('legs', 'Ноги'), ('core', 'Пресс/Кор'), ('cardio', 'Кардио'), ('other', 'Другое')], default='other', max_length=30)),
                ('equipment', models.CharField(choices=[('barbell', 'Штанга'), ('dumbbell', 'Гантели'), ('machine', 'Тренажёр'), ('cable', 'Блок'), ('bodyweight', 'Без оборудования'), ('other', 'Другое')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('how_to', models.TextField(blank=True, help_text='Техника выполнения (markdown)')),
                ('benefits', models.TextField(blank=True, help_text='Польза упражнения')),
                ('tips', models.TextField(blank=True, help_text='Советы и ошибки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='exercises/gifs/')),
                ('video_url', models.URLField(blank=True)),
                ('extra_links', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('body_region', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['body_region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('week_index', models.PositiveSmallIntegerField(default=0)),
                ('day_index', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rest_day', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['week_index', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fitness.trainingday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-started'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weeks_count', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='fitness.trainingprogram'),
        ),
        migrations.CreateModel(
            name='SessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('orm', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('day_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.dayexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.workoutsession')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='DaySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fitness.trainingday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise'),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.daysection'),
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.PositiveSmallIntegerField(choices=[(1, 'Немного'), (2, 'Средне'), (3, 'Сильно'), (4, 'Очень сильно')], default=2)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='fitness.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.musclegroup')),
            ],
            options={
                'unique_together': {('exercise', 'muscle')},
            },
        ),
    ]
