# Generated by Django 4.2.9 on 2026-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['body_region', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='common_mistakes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='emoji',
            field=models.CharField(blank=True, default='🏋️', max_length=10),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='benefits',
            field=models.TextField(blank=True, help_text='Зачем её развивать'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='daily_life',
            field=models.TextField(blank=True, help_text='Где в жизни используется'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='description',
            field=models.TextField(blank=True, help_text='Что это за мышца, где находится'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='emoji',
            field=models.CharField(blank=True, default='💪', max_length=10),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='functions',
            field=models.TextField(blank=True, help_text='Что она делает анатомически'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='muscles/'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='posture_role',
            field=models.TextField(blank=True, help_text='Роль в осанке и здоровье'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='how_to',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tips',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='body_region',
            field=models.CharField(blank=True, choices=[('chest', 'Грудь'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('arms', 'Руки'), ('legs', 'Ноги'), ('core', 'Пресс/Кор'), ('other', 'Другое')], max_length=50),
        ),
    ]
