# Generated by Django 4.2.9 on 2026-03-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_musclegroup_options_exercise_common_mistakes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayexercise',
            name='measurement_type',
            field=models.CharField(blank=True, help_text='Переопределяет тип из упражнения если задан', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='measurement_type',
            field=models.CharField(choices=[('strength', 'Силовой (кг × повторения)'), ('running', 'Беговой (м + время)'), ('reps', 'Повторения'), ('time', 'Время (сек)'), ('distance', 'Дистанция (м)'), ('standard', 'Произвольное число')], default='strength', max_length=20),
        ),
    ]
