# Generated by Django 4.2.9 on 2026-03-22 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('standard', 'standard'), ('strength', 'strength')], default='standard', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(default='#1677ff', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.progresscategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StrengthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('orm', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_records', to='progress.progresstracker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='progress.progresstracker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
