# Generated by Django 6.0.3 on 2026-04-03 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#e8003d', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_hardcore', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_type', models.CharField(choices=[('code', 'Code'), ('brush', 'Brush'), ('sword', 'Sword'), ('brain', 'Brain'), ('star', 'Star'), ('bolt', 'Bolt'), ('trophy', 'Trophy'), ('fire', 'Fire'), ('target', 'Target'), ('book', 'Book'), ('music', 'Music'), ('camera', 'Camera'), ('globe', 'Globe'), ('cpu', 'CPU'), ('palette', 'Palette')], default='star', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#7c3aed', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_type', models.CharField(choices=[('code', 'Code'), ('brush', 'Brush'), ('sword', 'Sword'), ('brain', 'Brain'), ('star', 'Star'), ('bolt', 'Bolt'), ('trophy', 'Trophy'), ('fire', 'Fire'), ('target', 'Target'), ('book', 'Book'), ('music', 'Music'), ('camera', 'Camera'), ('globe', 'Globe'), ('cpu', 'CPU'), ('palette', 'Palette')], default='star', max_length=30)),
                ('xp_reward', models.IntegerField(default=500)),
                ('order', models.IntegerField(default=0)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('achievement_name', models.CharField(blank=True, max_length=100)),
                ('achievement_description', models.TextField(blank=True)),
                ('achievement_icon', models.CharField(blank=True, default='🏆', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='skills.branch')),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='skills.checkpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='skills.direction'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(blank=True)),
                ('xp_reward', models.IntegerField(default=100)),
                ('difficulty_rating', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('hardcore_xp_multiplier', models.FloatField(default=2.0)),
                ('hardcore_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='skills.checkpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
