# Generated by Django 6.0.3 on 2026-04-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='branch',
            name='hardcore_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_variant', to='skills.branch'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='skills.checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='pos_x',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='pos_y',
            field=models.IntegerField(default=400),
        ),
    ]
